export const Projects=[
    {
"title":"Talent Trove",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
{"title":"Social Media App",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
{"title":"GameGear",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
{"title":"Music Player",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
{"title":"Food Ordering",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
{"title":"Project Managment App",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
{"title":"Relaxtion App",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
{"title":"Blogging Platform",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
{"title":"Language Learning App",
"Description":"",
"Tech Stack":[],
"Docs":"",
"Github":"",
"Demo":"",
"Level":1
    },
]